export const products = [
    {
        id: 1,
        category: 'tv',
        title: 'Телевізор Samsung UE50DU7100UXUA',
        img: 'https://content.rozetka.com.ua/goods/images/big/504736991.jpg',
        price: 19999,
    },
    {
        id: 2,
        category: 'tv',
        title: 'Телевізор Samsung UE50DU7100UXUA',
        img: 'https://content.rozetka.com.ua/goods/images/big/504736991.jpg',
        price: 19999,
    },
    {
        id: 3,
        category: 'tv',
        title: 'Телевізор Samsung UE50DU7100UXUA',
        img: 'https://content.rozetka.com.ua/goods/images/big/504736991.jpg',
        price: 19999,
    },
    {
        id: 4,
        category: 'tv',
        title: 'Телевізор Samsung UE50DU7100UXUA',
        img: 'https://content.rozetka.com.ua/goods/images/big/504736991.jpg',
        price: 19999,
    },
    {
        id: 5,
        category: 'laptops',
        title: 'Ноутбук Lenovo IdeaPad 1 15IAU7',
        img: 'https://content1.rozetka.com.ua/goods/images/big/476568545.jpg',
        price: 21599,
    },
    {
        id: 6,
        category: 'laptops',
        title: 'Ноутбук Lenovo IdeaPad 1 15IAU7',
        img: 'https://content1.rozetka.com.ua/goods/images/big/476568545.jpg',
        price: 21599,
    },
    {
        id: 7,
        category: 'laptops',
        title: 'Ноутбук Lenovo IdeaPad 1 15IAU7',
        img: 'https://content1.rozetka.com.ua/goods/images/big/476568545.jpg',
        price: 21599,
    },
    {
        id: 8,
        category: 'laptops',
        title: 'Ноутбук Lenovo IdeaPad 1 15IAU7',
        img: 'https://content1.rozetka.com.ua/goods/images/big/476568545.jpg',
        price: 21599,
    },
    {
        id: 9,
        category: 'smartphones',
        title: 'Мобільний телефон Samsung Galaxy S25 Ultra',
        img: 'https://content1.rozetka.com.ua/goods/images/big/507062959.jpg',
        price: 67999,
    },
    {
        id: 10,
        category: 'smartphones',
        title: 'Мобільний телефон Samsung Galaxy S25 Ultra',
        img: 'https://content1.rozetka.com.ua/goods/images/big/507062959.jpg',
        price: 67999,
    },
    {
        id: 11,
        category: 'smartphones',
        title: 'Мобільний телефон Samsung Galaxy S25 Ultra',
        img: 'https://content1.rozetka.com.ua/goods/images/big/507062959.jpg',
        price: 67999,
    },
    {
        id: 12,
        category: 'smartphones',
        title: 'Мобільний телефон Samsung Galaxy S25 Ultra',
        img: 'https://content1.rozetka.com.ua/goods/images/big/507062959.jpg',
        price: 67999,
    },
    {
        id: 13,
        category: 'screens',
        title: 'Монітор 27" Samsung Odyssey G50D',
        img: 'https://content1.rozetka.com.ua/goods/images/big/440994724.jpg',
        price: 10899,
    },
    {
        id: 14,
        category: 'screens',
        title: 'Монітор 27" Samsung Odyssey G50D',
        img: 'https://content1.rozetka.com.ua/goods/images/big/440994724.jpg',
        price: 10899,
    },
    {
        id: 15,
        category: 'screens',
        title: 'Монітор 27" Samsung Odyssey G50D',
        img: 'https://content1.rozetka.com.ua/goods/images/big/440994724.jpg',
        price: 10899,
    },
    {
        id: 16,
        category: 'screens',
        title: 'Монітор 27" Samsung Odyssey G50D',
        img: 'https://content1.rozetka.com.ua/goods/images/big/440994724.jpg',
        price: 10899,
    },
]
